config/routes.rb
Html5::Application.routes.draw do

  match 'canvas/bounce' => 'canvas#bounce', :as => :bounce
  match 'canvas/grid' => 'canvas#grid', :as => :grid

   root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController

  before_filter :set_canvas_size

  def bounce
    @title = "Bouncing Ball Demo"
  end

  def grid
    @title = "Grid traversal demo"
    @canvas_width = @canvas_height
  end

  def set_canvas_size
    @canvas_width = params[:cw] || 1000
    @canvas_height = params[:ch] || 600
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canvas_helper.rb
module CanvasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/canvas/bounce.html.erb
<% content_for :title do %>
    <h2>A Simple Bouncing Ball with Adjustable Slope</h2>
<% end %>

<div id="controls">
  <div>Angle: <span id="angle"></span> degrees, Location: (<span id="x-pos"></span>, <span id="y-pos"></span>)</div>

  X: <input type="text" id="x" value="10">
  Y: <input type="text" id="y" value="5">
  <input type="button" value="Reload" onclick="init();"/>
</div>

<script type="text/javascript">
    var radius = 15;
    var width = 1000;
    var height = 600;
    var x = 400;
    var y = 500;
    var dx = parseInt(document.getElementById("x").value);
    var dy = parseInt(document.getElementById("y").value);

    function init() {
        dx = parseInt(document.getElementById("x").value);
        dy = parseInt(document.getElementById("y").value);

        // Call the function every once and a while
        setInterval("move()", 40);
    }

    function move() {

        // Check for collisions with the edges
        if (x > (width - radius)) {
            dx = Math.abs(dx) * -1;
        } // Make it go left
        if (x < radius) {
            dx = Math.abs(dx);
        } // Make it go right
        if (y > (height - radius)) {
            dy = Math.abs(dy) * -1;
        } // Make it go up
        if (y < radius) {
            dy = Math.abs(dy)
        } // Make it go down

        // Move the ball
        x += dx;
        y += dy;

        // Update the screen
        draw(x, y);

        // Update the angle
        document.getElementById("angle").innerHTML = Math.round(Math.atan(dy / dx) * (180 / Math.PI));
        document.getElementById("x-pos").innerHTML = x;
        document.getElementById("y-pos").innerHTML = y;

    }

    function draw(x, y) {

        // Get our canvas
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Erase the board
        ctx.clearRect(0, 0, width, height);

        // Draw the circle
        ctx.fillStyle = "#336699";
        ctx.beginPath();
        ctx.arc(x, y, radius, 0, Math.PI * 2, true);
        ctx.closePath();
        ctx.fill();
    }

    init();


</script>

app/views/canvas/grid.html.erb
<% content_for :title do %>
    <h2>An Example of ways to travel a grid.</h2>
<% end %>

<div id="controls">
  <input type="button" value="Reload" onclick="init();"/>
</div>


<script type="text/javascript" language="javascript">
    var width = <%= @canvas_width %>;
    var height = <%= @canvas_height %>;
    var boxes = 13;
    var offset = 3;
    var boxsize = width / 14;

    var canvas = document.getElementById("canvas");
    var context = canvas.getContext("2d");

    var grid = [];


    function init() {

        for (var i = 0; i < boxes; i++) {
            grid[i] = [];
            for (var j = 0; j < boxes; j++) {
                // Initialize the array with all 0s

                grid[i][j] = 0;
                drawSquare(i,j)
            }
        }

        // Reset the timers

    }

    function drawSquare(x, y) {
        if (grid[x][y] == 1) {
            context.fillStyle = "#66FF33";
        } else {
            context.fillStyle = "#336633";
        }
        context.fillRect((x * boxsize) + (x * offset) + offset, (y * boxsize) + (y * offset) + offset, boxsize, boxsize);
    }


    init();


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">
  <div id="title">
    <%= yield :title %>
  </div>
  <div id="main">
    <canvas id="canvas" width="<%= @canvas_width %>" height="<%= @canvas_height %>">
      Your browser does not support the canvas element.
    </canvas>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<% content_for :title do %>
<h2>Welcome! This project serves as a series of warm up exercises around simply animation concepts.
</h2>
<ul>
  <li><%= link_to "Bouncing Ball", bounce_path %><span>A simple demonstration of a bouncing ball with controllable slope.</span></li>
</ul>
<% end %>

<script type="text/javascript">
function draw() {
	// Get our canvas
	var c = document.getElementById("myCanvas");
	var ctx = c.getContext("2d");
	for(i = 0; i < 100; i++) {
		   ctx.beginPath();
	       ctx.moveTo(Math.floor(Math.random()*1000), Math.floor(Math.random()*600));
	       ctx.lineTo(Math.floor(Math.random()*100), Math.floor(Math.random()*600));
	       ctx.stroke();
	}	
}

setTimeout('draw()', 500);

</script>